[rpcclientconfig]
;是否允许单元测试
unittest = 1

[powermangeconfig]
;唤醒是否网络请求 0 不请求 1 请求
wakeupnetstatus = 0

;睡眠通知是否睡眠 0 睡眠 1 不睡眠
sleeptspstatus = 0

;mcu查询是否网络请求 0 不请求 1 请求
mcunetstatus = 0

;睡眠通知后否网络请求 0 不请求 1 请求
sleepconfirmnetstatus = 0

;是否请求上报CAN数据 0 不上传 1上传
canLogStatus = 1

;是否允许蓝牙循环测试   0不允许  1允许
btTestStatus = 1

;蓝牙循环测试压力（单位s）
btTestPeriod = 5

[periodmessageconfig]
;参数依次是
;CanID（十进制）
;循环周期（必须大于5000us小于9999us，如该通道不参与测试，时间改为0即可）
;数据是否随机（0：不随机， 1随机）
CanCh_0 = 0001-0000-01
CanCh_1 = 0002-0000-01
CanCh_2 = 0003-0000-01
CanCh_3 = 0004-0000-01
CanCh_4 = 0005-0000-01
