[localstoreperiod]
localstoreperiod               = 1000


[normalreportperiod]
normalreportperiod             = 10


[alarmreportperiod]
alarmreportperiod              = 1000


[remoteserverdomainlen]
remoteserverdomainlen          = 50


[remotesrverdomainpara]
remotesrverdomainpara          = oneiot


[remotesrverdomainport]
remotesrverdomainport          = 7134


[hrversion]
hrversion                      = 1.2


[swversion]
swversion                      = 1.0


[heartbeatperiod]
heartbeatperiod                = 5


[tboxacktimeout]
tboxacktimeout                 = 5


[seviceacktimeout]
seviceacktimeout               = 5


[nextloginperiod]
nextloginperiod                = 30


[commonservicedomainlen]
commonservicedomainlen         = 50


[commonserverdomainpara]
commonserverdomainpara         = oneiot


[commonServerDomainIP]
commonServerDomainIP           = 171.217.92.76

[commonserverdomainport]
;commonserverdomainport         = 7134
commonserverdomainport         = 9235


[samplemonitor]
samplemonitor                  = 2

[loginsn]
loginsn                        = 1

[loginday]
loginday                       = 1

[vin]
vin                            = SINGULATO00000001

[rxprintf]
rxprintf                       = 1


[txprintf]
txprintf                       = 1

[encryptType]
encryptType                    = 1

[registerFlag]
registerFlag                   = 0