;VERSION
[fileVersion]

Version = 8.1;

[CANID_Total]

;Upload ID total num, max 200
CANIDtotal = 104

[CANID_Msg]
;Channel EV CAN1:0; CH CAN2:1; BD CAN3:2; CAN4:3;
CANCH_1        = 2
CANID_1        = 0x105
CANID_Cycle_1  = 1

CANCH_2        = 2
CANID_2        = 0x211
CANID_Cycle_2  = 1

CANCH_3        = 2
CANID_3        = 0x2B3
CANID_Cycle_3  = 1

CANCH_4        = 2
CANID_4        = 0x2F3
CANID_Cycle_4  = 1

CANCH_5        = 2
CANID_5        = 0x2F5
CANID_Cycle_5  = 1

CANCH_6        = 2
CANID_6        = 0x2F7
CANID_Cycle_6  = 1

CANCH_7        = 2
CANID_7        = 0x2F9
CANID_Cycle_7  = 1

CANCH_8        = 2
CANID_8        = 0x2FA
CANID_Cycle_8  = 1

CANCH_9        = 2
CANID_9        = 0x2FC
CANID_Cycle_9  = 1

CANCH_10       = 2
CANID_10       = 0x395
CANID_Cycle_10 = 1

CANCH_11       = 2
CANID_11       = 0x3B1
CANID_Cycle_11 = 1

CANCH_12       = 2
CANID_12       = 0x3B3
CANID_Cycle_12 = 1

CANCH_13       = 2
CANID_13       = 0x3FE
CANID_Cycle_13 = 1

CANCH_14       = 2
CANID_14       = 0x402
CANID_Cycle_14 = 1

CANCH_15       = 2
CANID_15       = 0x404
CANID_Cycle_15 = 1

CANCH_16       = 2
CANID_16       = 0x406
CANID_Cycle_16 = 1

CANCH_17       = 2
CANID_17       = 0x408
CANID_Cycle_17 = 1

CANCH_18       = 2
CANID_18       = 0x40A
CANID_Cycle_18 = 1

CANCH_19       = 2
CANID_19       = 0x410
CANID_Cycle_19 = 1

CANCH_20       = 2
CANID_20       = 0x412
CANID_Cycle_20 = 1

CANCH_21       = 2
CANID_21       = 0x414
CANID_Cycle_21 = 1

CANCH_22       = 2
CANID_22       = 0x418
CANID_Cycle_22 = 1

CANCH_23       = 2
CANID_23       = 0x3B5
CANID_Cycle_23 = 1

CANCH_24       = 2
CANID_24       = 0x3B7
CANID_Cycle_24 = 1

CANCH_25       = 2
CANID_25       = 0x2EF
CANID_Cycle_25 = 1

CANCH_26       = 2
CANID_26       = 0x2E4
CANID_Cycle_26 = 1

CANCH_27       = 2
CANID_27       = 0x3A5
CANID_Cycle_27 = 1

CANCH_28       = 2
CANID_28       = 0x24
CANID_Cycle_28 = 1

CANCH_29       = 1
CANID_29       = 0x21
CANID_Cycle_29 = 1

CANCH_30       = 1
CANID_30       = 0x104
CANID_Cycle_30 = 1

CANCH_31       = 1
CANID_31       = 0x107
CANID_Cycle_31 = 1

CANCH_32       = 1
CANID_32       = 0x109
CANID_Cycle_32 = 1

CANCH_33       = 1
CANID_33       = 0x10A
CANID_Cycle_33 = 1

CANCH_34       = 1
CANID_34       = 0x117
CANID_Cycle_34 = 1

CANCH_35       = 1
CANID_35       = 0x123
CANID_Cycle_35 = 1

CANCH_36       = 1
CANID_36       = 0x125
CANID_Cycle_36 = 1

CANCH_37       = 1
CANID_37       = 0x131
CANID_Cycle_37 = 1

CANCH_38       = 1
CANID_38       = 0x264
CANID_Cycle_38 = 1

CANCH_39       = 1
CANID_39       = 0x91
CANID_Cycle_39 = 1

CANCH_40       = 1
CANID_40       = 0x92
CANID_Cycle_40 = 1

CANCH_41       = 1
CANID_41       = 0x93
CANID_Cycle_41 = 1

CANCH_42       = 1
CANID_42       = 0x95
CANID_Cycle_42 = 1

CANCH_43       = 0
CANID_43       = 0x1F7
CANID_Cycle_43 = 1

CANCH_44       = 0
CANID_44       = 0x200
CANID_Cycle_44 = 1

CANCH_45       = 0
CANID_45       = 0x224
CANID_Cycle_45 = 1

CANCH_46       = 0
CANID_46       = 0x244
CANID_Cycle_46 = 1

CANCH_47       = 0
CANID_47       = 0x246
CANID_Cycle_47 = 1

CANCH_48       = 0
CANID_48       = 0x248
CANID_Cycle_48 = 1

CANCH_49       = 0
CANID_49       = 0x249
CANID_Cycle_49 = 1

CANCH_50       = 0
CANID_50       = 0x260
CANID_Cycle_50 = 1

CANCH_51       = 0
CANID_51       = 0x262
CANID_Cycle_51 = 1

CANCH_52       = 0
CANID_52       = 0x268
CANID_Cycle_52 = 1

CANCH_53       = 0
CANID_53       = 0x26C
CANID_Cycle_53 = 1

CANCH_54       = 0
CANID_54       = 0x26E
CANID_Cycle_54 = 1

CANCH_55       = 0
CANID_55       = 0x297
CANID_Cycle_55 = 1

CANCH_56       = 0
CANID_56       = 0x2E8
CANID_Cycle_56 = 1

CANCH_57       = 0
CANID_57       = 0x301
CANID_Cycle_57 = 1

CANCH_58       = 0
CANID_58       = 0x311
CANID_Cycle_58 = 1

CANCH_59       = 0
CANID_59       = 0x3E5
CANID_Cycle_59 = 1

CANCH_60       = 0
CANID_60       = 0x3E7
CANID_Cycle_60 = 1

CANCH_61       = 0
CANID_61       = 0x3FD
CANID_Cycle_61 = 1

CANCH_62       = 0
CANID_62       = 0x97
CANID_Cycle_62 = 1

CANCH_63       = 0
CANID_63       = 0x99
CANID_Cycle_63 = 1

CANCH_64       = 0
CANID_64       = 0x3E6
CANID_Cycle_64 = 1

CANCH_65       = 0
CANID_65       = 0x254
CANID_Cycle_65 = 1

CANCH_66       = 0
CANID_66       = 0x312
CANID_Cycle_66 = 1

CANCH_67       = 0
CANID_67       = 0x3A1
CANID_Cycle_67 = 1

CANCH_68       = 2
CANID_68       = 0x2B0
CANID_Cycle_68 = 1

CANCH_69       = 1
CANID_69       = 0x118
CANID_Cycle_69 = 1

CANCH_70       = 1
CANID_70       = 0x140
CANID_Cycle_70 = 1

CANCH_71       = 1
CANID_71       = 0x215
CANID_Cycle_71 = 1

CANCH_72       = 0
CANID_72       = 0x103
CANID_Cycle_72 = 1

CANCH_73       = 0
CANID_73       = 0x028
CANID_Cycle_73 = 1

CANCH_74       = 0
CANID_74       = 0x106
CANID_Cycle_74 = 1

CANCH_75       = 1
CANID_75       = 0x119
CANID_Cycle_75 = 1

CANCH_76       = 0
CANID_76       = 0x3E1
CANID_Cycle_76 = 1

CANCH_77       = 0
CANID_77       = 0x252
CANID_Cycle_77 = 1

CANCH_78       = 0
CANID_78       = 0x226
CANID_Cycle_78 = 1

CANCH_79       = 0
CANID_79       = 0x12F
CANID_Cycle_79 = 1

CANCH_80       = 0
CANID_80       = 0x207
CANID_Cycle_80 = 1

CANCH_81       = 0
CANID_81       = 0x320
CANID_Cycle_81 = 1

CANCH_82       = 0
CANID_82       = 0x209
CANID_Cycle_82 = 1

CANCH_83       = 0
CANID_83       = 0x111
CANID_Cycle_83 = 1

CANCH_84       = 0
CANID_84       = 0x113
CANID_Cycle_84 = 1

CANCH_85       = 0
CANID_85       = 0x205
CANID_Cycle_85 = 1

CANCH_86       = 0
CANID_86       = 0x323
CANID_Cycle_86 = 1

CANCH_87       = 0
CANID_87       = 0x115
CANID_Cycle_87 = 1

CANCH_88       = 0
CANID_88       = 0x12B
CANID_Cycle_88 = 1

CANCH_89       = 0
CANID_89       = 0x12D
CANID_Cycle_89 = 1

CANCH_90       = 0
CANID_90       = 0x203
CANID_Cycle_90 = 1

CANCH_91       = 0
CANID_91       = 0x127
CANID_Cycle_91 = 1

CANCH_92       = 0
CANID_92       = 0x129
CANID_Cycle_92 = 1

CANCH_93       = 0
CANID_93       = 0x230
CANID_Cycle_93 = 1

CANCH_94       = 0
CANID_94       = 0x243
CANID_Cycle_94 = 1

CANCH_95       = 0
CANID_95       = 0x3FF
CANID_Cycle_95 = 1

CANCH_96       = 0
CANID_96       = 0x120
CANID_Cycle_96 = 1

CANCH_97       = 1
CANID_97       = 0x13A
CANID_Cycle_97 = 1

CANCH_98       = 1
CANID_98       = 0x13C
CANID_Cycle_98 = 1

CANCH_99       = 1
CANID_99       = 0x270
CANID_Cycle_99 = 1

CANCH_100       = 0
CANID_100       = 0x330
CANID_Cycle_100 = 1

CANCH_101       = 1
CANID_101       = 0x2C0
CANID_Cycle_101 = 1

CANCH_102       = 1
CANID_102        = 0x2C1
CANID_Cycle_102 = 1

CANCH_103       = 2
CANID_103        = 0x135
CANID_Cycle_103 = 1

CANCH_104       = 0
CANID_104        = 0x3D6
CANID_Cycle_104 = 1