[CANID_Total]

;Max 50 ID
CANIDtotal = 35

[CANID_Msg]
;MCU
CANREQ_1       = 0x710
CANREP_1       = 0x790	 
CANCH_1		   = 0
	
;BMS
CANREQ_2       = 0x711
CANREP_2       = 0x791	
CANCH_2		   = 0

;EAC
CANREQ_3       = 0x712
CANREP_3       = 0x792
CANCH_3		   = 0

;CDU
CANREQ_4       = 0x713
CANREP_4       = 0x793
CANCH_4		   = 0

;VTMS
CANREQ_5       = 0x714
CANREP_5       = 0x794
CANCH_5		   = 0

;PTC
CANREQ_6       = 0x715
CANREP_6       = 0x795
CANCH_6		   = 0

;SSW
CANREQ_7       = 0x720
CANREP_7       = 0x7A0
CANCH_7		   = 0

;PM2.5
CANREQ_8       = 0x721
CANREP_8       = 0x7A1	
CANCH_8		   = 0

;VCU
CANREQ_9       = 0x722
CANREP_9       = 0x7A2
CANCH_9		   = 0

;ESP
CANREQ_10      = 0x723
CANREP_10      = 0x7A3
CANCH_10	   = 1
					
;lbooster
CANREQ_11      = 0x724
CANREP_11      = 0x7A4
CANCH_11	   = 1

;ADAS_RAD
CANREQ_12      = 0x725
CANREP_12      = 0x7A5
CANCH_12	   = 1

;ADAS_CAM
CANREQ_13      = 0x726
CANREP_13      = 0x7A6
CANCH_13	   = 1

;ACU
CANREQ_14      = 0x7F1
CANREP_14      = 0x7F9
CANCH_14	   = 1

;APA
CANREQ_15      = 0x728
CANREP_15      = 0x7A8
CANCH_15	   = 1

;EPS
CANREQ_16      = 0x729
CANREP_16      = 0x7A9
CANCH_16	   = 1

;IHU
CANREQ_17      = 0x72A
CANREP_17      = 0x7AA
CANCH_17	   = 2

;SMM
CANREQ_18      = 0x72B
CANREP_18      = 0x7AB
CANCH_18	   = 2

;AVM
CANREQ_19      = 0x72C
CANREP_19      = 0x7AC
CANCH_19	   = 2

;TPMS
CANREQ_20      = 0x72D
CANREP_20      = 0x7AD
CANCH_20	   = 2

;WCM
CANREQ_21      = 0x72E
CANREP_21      = 0x7AE
CANCH_21	   = 2

;PLG
CANREQ_22      = 0x72F
CANREP_22      = 0x7AF
CANCH_22	   = 2

;CCS
CANREQ_23      = 0x730
CANREP_23      = 0x7B0
CANCH_23	   = 2

;BCM
CANREQ_24      = 0x731
CANREP_24      = 0x7B1
CANCH_24	   = 2

;ICM
CANREQ_25      = 0x732
CANREP_25      = 0x7B2
CANCH_25	   = 2

;TBOX
CANREQ_26      = 0x733
CANREP_26      = 0x7B3
CANCH_26	   = 2

;APL
CANREQ_27      = 0x734
CANREP_27      = 0x7B4
CANCH_27	   = 2

;GW
CANREQ_28      = 0x735
CANREP_28      = 0x7B5
CANCH_28	   = 2

;PPD
CANREQ_29      = 0x736
CANREP_29      = 0x7B6
CANCH_29	   = 2

;VCU_HTI
CANREQ_30      = 0x7E2
CANREP_30      = 0x7EA
CANCH_30	   = 0

;EMS_HTI
CANREQ_31      = 0x7E0
CANREP_31      = 0x7E8
CANCH_31	   = 0

;MCU_HTI
CANREQ_32      = 0x7E3
CANREP_32      = 0x7EB
CANCH_32	   = 0

;GCU_HTI
CANREQ_33      = 0x7E6
CANREP_33      = 0x7EE
CANCH_33	   = 0

;EHBi
CANREQ_34      = 0x744
CANREP_34      = 0x7C4
CANCH_34	   = 0

;BSD
CANREQ_35      = 0x745
CANREP_35      = 0x7C5
CANCH_35	   = 1

