;#mode 1:SmartCharge 2 ChargeImmediately
[chargeMode]
mode            = 2

[charge]
flag            = 0
mode            = 1
start           = FFFFFFFFFFFF
stop            = FFFFFFFFFFFF
soc             = FF

[air]
flag            = 0
start           = FFFFFFFFFFFF
ctlSw           = 0
windMode        = 0
defrostSw       = 0
acSw            = 0
autoMode        = 0
temp1           = 0
temp2           = 0
wind1           = 0
wind2           = 0
loop            = 0
anion           = 0
pm25            = 0
