[upgradeType]
;type:0为TBOX升级，1为ECU升级
Type = 0;

;密码使能,1为加密，0为不加密
PasswordEnable = 0;

;用来解密升级文件,密码长度为6
Password = xxxxxx;

[tboxRef]
;ARM升级使能,1为升级，0为不升级
ArmEnable = 1;

;MCU升级使能，1为升级，0为不升级
MCUEnable = 1

;MCU升级文件名
MCUFile = UserApp_md5.bin;

;蓝牙升级使能，1为升级，0为不升级
BTEnable = 0

;蓝牙升级文件名
BTFile = BtApp.bin;

;蓝牙定位模块升级使能，1为升级，0为不升级
BTSTBEnable =0

;蓝牙定位模块升级文件名
BTSTBFile = BtStbApp.bin;
[ECURef]
;ECU 类型
;0: AFS 1: BCM 2: APU 3: BMS 4: EDCM 5: EPB 6: ICM 7: MCS 8: SCM 9: VMS
ECUType = 0;

;ECU Driver升级使能，1为升级，0为不升级
ECUDriverEnable = 1;

;ECUDriver升级文件名
ECUDriverFile = xxxx;

;ECU APP升级使能，1为升级，0为不升级
ECUAPPEnable = 1
;ECUAPP升级文件名
ECUAPPFile = xxxx;

;等待时间(ms)
WaitTime = 1000;
